server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  redis:
    host: ec2-3-37-11-7.ap-northeast-2.compute.amazonaws.com # 서버주소 넣어야 함.
    port: 6379
  datasource:
    url: jdbc:mysql://finalproject.cdd2oclmksvc.ap-northeast-2.rds.amazonaws.com:3306/finalproject?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    '[shop.mtcoding.restend]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

file:
  path: ./upload/ # UPLOAD 폴더 상대경로 / AWS에 S3 사용하는게 좋음

SECRET_ACCESS: ${SECRET_ACCESS}
SECRET_REFRESH: ${SECRET_REFRESH}

EMAIL_PASSWORD: ${EMAIL_PASSWORD}