server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: finalproject
    key-alias: finalkey

spring:
  redis:
    host: 43.201.57.38 # 서버주소 넣어야 함.
    port: 6379
  datasource:
    url: jdbc:mysql://finalproject.cdd2oclmksvc.ap-northeast-2.rds.amazonaws.com:3306/finalproject?useSSL=false&setTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      default_batch_fetch_size: 100
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: money-bridge
    region:
      static: ap-northeast-2
    stack:
      auto: false
logging:
  level:
    '[kr.co.moneybridge]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

SECRET_ACCESS: ${SECRET_ACCESS}
SECRET_REFRESH: ${SECRET_REFRESH}

SYSMETIC_EMAIL_PASSWORD: ${SYSMETIC_EMAIL_PASSWORD}

DEFAULT_THUMBNAIL: "https://d2ky5wm6akosox.cloudfront.net/default/sample.svg"
DEFAULT_PROFILE: "https://d2ky5wm6akosox.cloudfront.net/default/profile.svg"

MB_CLIENT_ID: ${MB_CLIENT_ID}
MB_CLIENT_SECRET: ${MB_CLIENT_SECRET}